name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step to get the version number from CMakeLists.txt
      - name: Get version number
        id: get_version
        run: |
          VERSION=$(grep "Kuzu VERSION" kuzu/CMakeLists.txt | head -1 | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV


      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            dylanshang/kuzu-wasm:latest
            dylanshang/kuzu-wasm:${{ env.VERSION }}