name: 'shell'
on:
  workflow_dispatch:  
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14

    - uses: actions/setup-node@v4
      with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
    - run: npm install -g yarn
    - name: Build Shell Project
      run: |
        make shell
    - name: Run Benchmark
      run: |
        make benchmark

    - name: Upload Benchmark Report
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-report
        path: packages/benchmarks/benchmark_report.md

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: 'packages/kuzu-shell/dist'
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
        enable-github-deployment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 10


